### ISSUE TITLE
Archival file format ...?

### ISSUE THREAD

**Issue by jmhayes-table** [szpajder/libacars#4]
As this library grows and supports more message types, it might be nice to be able to go back to archived data and re-run a decoder on previously not-decoded messages (cf your comment about being "lazy" :) about AFN messages in the closed issue). What would you think about adding an archive output format that could "save" what has been demodulated for later analysis but an as-yet-unreleased decoder?

**Comment by szpajder** [comment]
Output files are not produced by libacars but by applications using it (dumpvdl2, JAERO, etc). Hence, libacars is not a place for such a feature. It should be implemented in the abovementioned apps.

On the other hand - I often decode messages from archived logs. I just extract the text part from ACARS messages of interest (using a script) and then pass it to decode_acars_apps or decode_arinc. So it's already possible. I see no need for having an additional log format for this purpose.
