### ISSUE TITLE
Support for sub label?

### ISSUE THREAD

**Issue by kevinelliott** [szpajder/libacars#5]
Some ACARS packets, specifically ones with `H1` labels, should have sub labels. Add support for decoding and storing the sub label.

(See: http://www.cosmic.com.au/acarsanalyser/v3/DataRes/MsgLabelsData.asp#sublabel for examples of sub labels)

**Comment by szpajder** [comment]
Hi Kevin,

This feature is on the TODO list. It will arrive together with ACARS block reassembly feature. Storing the sublabel requires a field to be added to `la_acars_msg` structure, but unfortunately I forgot to add some "reserved for future use" fields there, so it has to wait for a major release 2.0.0. Otherwise the ABI compatibility would not be preserved, which would cause apps compiled against libacars 1.x to break.

**Comment by kevinelliott** [comment]
Got it, Tomasz, that makes a lot of sense. Any thoughts on when that might happen? Anything I can do to help? (You might remember I wrote some JSON output support for dumpvdl2, which won’t be usable due to upcoming changes too).

**Comment by szpajder** [comment]
I think I'll make one more stable release in the 1.x series. It will introduce JSON support for all protocols supported by the library. The work is actually complete and already published in the unstable branch. The only application which makes use of the JSON API is, as of now, decode_acars_apps. Currently I'm in the process of rewriting protocol decoders and the output layer in dumpvdl2 to use la_proto_trees and la_vstrings. The work is about 80% complete. I'm holding the stable release of libacars just in case I need some last-minute changes in its API to complete the current work on dumpvdl2. I expect to finish this in a week or two and then the libacars release will come out. It might also be a good idea to release dumpvdl2 v. 1.7.0 then, however it won't be able to produce JSON output yet. Support for multiple outputs of various types and JSON support will go into dumpvdl2 1.8.0 (or maybe I'll call it 2.0.0... dunno yet). Numbermania aside - this is going to be a significant piece of work and libacars 2.0.0 won't happen before it's completed.... so 3rd, maybe even 4th quarter of 2019 seems to be a reasonable estimate for it.

**Comment by kevinelliott** [comment]
Thanks @szpajder ... let me know if there's anything else I can do to assist.

**Comment by szpajder** [comment]
Decoding of sublabel and MFI fields is now available in unstable branch.

**Comment by szpajder** [comment]
Released in v2.0.0.

Closing.
